# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0060_auto_20160901_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='机台吨位')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='生产订单号')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='物料代码')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='物料说明')),
                ('f05', models.CharField(default='.', max_length=99, verbose_name='材料')),
                ('f06', models.IntegerField(default=0, verbose_name='订单数量')),
                ('f07', models.IntegerField(default=0, verbose_name='未生产数量')),
                ('f08', models.FloatField(default=0, verbose_name='工时')),
                ('f09', models.FloatField(default=0, verbose_name='生产周期')),
                ('f10', models.FloatField(default=0, verbose_name='生产天数')),
            ],
        ),
        migrations.AlterField(
            model_name='item009',
            name='row08g03',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 無���修復'),
        ),
    ]
